CREATE DATABASE CRIMINAL;
CREATE TABLE represent(
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('1', '101', 'JOHN', '27', 'ROBBERY', '9441663280');
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('2', '142', 'ARUN', '34', 'CHILD ABUSE', '9032213694');
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('3', '123', 'AMAR', '24', 'MURDER', '9948076050');
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('4', '35', 'DRAVE', '25', 'ROBBERY', '6302542238');
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('5', '58', 'IMRAN', '15', 'KIDNAP', '6302457890');
INSERT INTO `represent` (`S.NO`, `CRIMINAL ID`, `NAME`, `AGE`, `CRIME`, `PHONE NUMBER`) VALUES ('6', '12', 'ARVA', '40', 'MURDER', '6302345579');